version: '3.9'

services:
  app:
    container_name: portfolio-backend
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    command: sh -c "npm run migration:run && npm run start:dev"
    env_file:
      - .env.development
    network_mode: host
    depends_on:
      - postgres
  postgres:
    image: postgres:15.2-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env.development
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: